# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"


$script = <<SCRIPT
Write-Host "It works !!!"
SCRIPT

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.guest = :windows 
  config.vm.box = "win2012-R2"
  config.vm.box_url = "file://{path_to_where_you_saved_the_box_file_local}/win2012-R2.box"

  config.vm.network "private_network", ip: "192.168.50.4"
  config.vm.network :forwarded_port, guest: 3389, host: 33389, id: "rdp", auto_correct: true
  config.vm.communicator = "winrm"

  config.vm.provision "shell", inline: $script
end
